### ISSUE TITLE
USER STORY: <Easy Navigation -- School Student >

### ISSUE THREAD

**Issue by AmberRoseA** [AmberRoseA/TaskToad#2]
As a **high school student** I can **easily navigate through my task management app** so that **I can manage my academic workload effectively and achieve good grades.**

## Acceptance Criteria:

*  Acceptance Criteria 1: Clear navigation with main elements displayed 
*  Acceptance Criteria 2: Drop Down options
*  Acceptance Criteria 3: Style format remains the same for different devices.

## Task 
- [ ] Task 1: Working navigation bar with pathway to chosen pages
- [ ] Task 2: CSS style implemented for best user experience 
- [ ] Task 3: Style for multiple screen devices
- [ ] Task 4: Test Functionality
