### ISSUE TITLE
USER STORY: <Marking Tasks importance-- University Student>

### ISSUE THREAD

**Issue by AmberRoseA** [AmberRoseA/TaskToad#5]
As a **university student** I can **prioritise my coding projects by marking their importance** so that **keep on top of projects and be aware of important tasks, deadline and work accordingly**

## Acceptance Criteria:

*  Acceptance Criteria 1: User can mark a task as important
*  Acceptance Criteria 2: Importance section in app, shows only tasks that user marked as important 
*  Acceptance Criteria 3: User can edit, delete, mark as completed.

## Task 
- [ ] Task 1: Give tasks importance option (sliding bar)
- [ ] Task 2: HTML file Important - Shows list of every task highlighted as important
- [ ] Task 3: Display in order of duedate
- [ ] Task 4: Test Functionality
