### ISSUE TITLE
USER STORY: <Signing and Login to Task management site -- Business owner >

### ISSUE THREAD

**Issue by AmberRoseA** [AmberRoseA/TaskToad#8]
As a **small business owner** I can **easily sign up and log into at task management app ** so that **I can get started in using the site straight away to help manage my business**

## Acceptance Criteria:

*  Acceptance Criteria 1: Signup and login requirements easily displayed 
*  Acceptance Criteria 2: Error, incorrect input when fields have not been filled out correctly 
*  Acceptance Criteria 3: Confirmation request when wanting to create account 

## Task 
- [ ] Task 1: Create HTML and CSS for Sign up and login page
- [ ] Task 2: Add requirements for valid inputs for name, email, password ect
- [ ] Task 3: Create error display pop up alerts and Confirmation pop ups
- [ ] Task 4: Test the functionality
